expected_output:
  - The crashpod or might mention the pod 'crashpod-9688789bc-lgjzj'. Mentioning one of the reasons for a CrashLoopBackOff state. 1. due to command 'wget' exiting with code 125 2. having recursive calls 3. StackOverflowError in the application.
  - workload_healthy flag should be false
before_test: |
  kubectl apply -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/main/crashpod/broken.yaml
  sleep 60
after_test: |
  kubectl delete -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/main/crashpod/broken.yaml
evaluation:
  correctness: 1
# Success rate 100% for 100 evals


