{"toolset_name":"kubernetes/logs","tool_name":"kubectl_logs","match_params":{"pod_name":"client","namespace":"investigate-namespace-15"}}
{"schema_version": "robusta:v1.0.0", "status": "success", "error": null, "return_code": 0, "data": null, "url": null, "invocation": "kubectl logs client -n investigate-namespace-15", "params": {"pod_name": "client", "namespace": "investigate-namespace-15"}}
Starting connection tests to http://nginx-service.test-ns
Press Ctrl+C to stop the client
Success! Status Code: 200, Time: 2025-06-20 13:14:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966fb6e90>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:14:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966fb7890>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:14:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966fc3ce0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966fc3100>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5967033410>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5040>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6030>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6250>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:15:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6470>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6690>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc68b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6ad0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6cf0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6f10>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:16:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7130>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7350>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7570>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7570>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7350>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7130>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:17:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6f10>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6cf0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6ad0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc68b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6690>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6470>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:18:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6250>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5260>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4f30>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6030>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4050>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5590>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:19:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5370>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5150>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5370>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5590>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4050>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6030>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:20:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4f30>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5260>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6250>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6470>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6690>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc68b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:21:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6ad0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6cf0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6f10>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7130>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7350>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7570>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:22:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7570>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7350>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7130>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6f10>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6cf0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6ad0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:23:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc68b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6690>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:10
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6470>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:20
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6250>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:30
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5260>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:40
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4f30>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:24:50
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6030>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:00
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4050>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5590>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5370>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc59d0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5040>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:25:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc58c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc57b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6140>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4e20>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc46b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6360>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:26:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6580>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc67a0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc69c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6be0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6e00>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7020>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:27:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7240>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7460>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7680>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7680>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7460>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7240>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:28:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7020>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6e00>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6be0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc69c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc67a0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6580>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:29:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6360>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc46b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4e20>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6140>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc57b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc58c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:30:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5040>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5040>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc58c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc57b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6140>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4e20>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:31:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc46b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6360>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6580>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc67a0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc69c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6be0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:32:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6e00>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7020>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7240>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7460>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7680>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5480>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:33:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc5480>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7680>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7460>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7240>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7020>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6e00>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:34:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6be0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc69c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc67a0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6580>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6360>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc46b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:35:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4e20>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6140>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc57b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc58c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc58c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc57b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:36:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6140>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc4e20>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc46b0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6360>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6580>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc67a0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:37:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc69c0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:01
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6be0>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:11
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc6e00>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:21
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7020>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:31
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7240>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:41
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7460>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:38:51
Connection error: HTTPConnectionPool(host='nginx-service.test-ns', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5966dc7680>: Failed to resolve 'nginx-service.test-ns' ([Errno -3] Try again)")) - Time: 2025-06-20 13:39:01
